language: python
python:
- '2.7'
- '3.6'
services:
  - docker
notifications:
  email: false
sudo: false
install:
- pip install -e .
script:
- python -c "import tools.msg as m; m.msg()"
deploy:
  - provider: pypi
    user: $PYPI_MAINTAINER_NAME
    password: $PYPI_MAINTAINER_PASS
    on:
      tags: true
      python: 3.6
    allow_failure: false
    skip_cleanup: true
  - provider: script
    script: bash .travis/docker_push.sh
    on:
      tags: true
      python: 3.6
    allow_failure: false
