language: python
python:
- '2.7'
- '3.6'
notifications:
  email: false
sudo: false
install:
- pip install -e .
script:
- python -c "import tools.msg as m; m.msg()"
deploy:
  provider: pypi
  user: $PYPI_DEPLOY_USER
  password: $PYPI_DEPLOY_PASS
  before_deploy: npm install
  on:
    condition: '`git describe --abbrev=0 --tags` != v`python -c "import tools._version; print(tools._version.__version__)"`'
    python: 3.6
  allow_failure: false
